### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by a7t0fwa7** [himanshu662000/InfoGPT#3]
Hey Mister Himanshu, thanks for putting this together I was working on a similar project, quick question, can code files such as .c, .cpp. rb etc.. also be uploaded as they are from what I understand just text files. Within the ingest.py file I see that you specify the different file extensions explicitly within the dictionary, do you suggest we do the same for the code formats?

Cheers

**Comment by himanshu662000** [comment]
Hi, I've tested it, and it works well for small files (like the util.py file in this project). However, I believe it might not perform as well with larger code files. Below is the result I got for python file using PythonLoader from langchain(util.py file in this project), please let me know what is your requirement and we can discuss what can be the possible approach we can take regarding this. Thanks!
![image](https://github.com/himanshu662000/InfoGPT/assets/53088534/a68dc920-21bf-4ee7-bf4f-77309a1de5ba)
![image](https://github.com/himanshu662000/InfoGPT/assets/53088534/22a397e1-88ba-4dc9-83b4-d20c1c5a6147)

**Comment by a7t0fwa7** [comment]
Thanks Himanshu, essentialy I am looking at having a chatbot capable of reading any filetypes including code files for research and learning purposes, I am learning about LLMs and sometimes the code logic is not clear so I like asking my chatbot for explanations and potential improvements etc. I have different file types i would like to have the vector DB ingest and so I need to have the bot able to read those different file types. :) i hope that clarifies things for you. 
Cheers
